version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_ssr
    ports:
      - 8001:80
    volumes:
      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/nginx:/var/www/html
    depends_on:
      - ztsphp

  ztsphp:
    build: ${PWD}/ztsphp
    container_name: ztsphp_ssr
    volumes:
      - ${PWD}/ztsphp:/var/www/html
    command: bash -c "chmod 777 /var/www/html && php-fpm"
